name: Compiles only

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: wget
      run: mkdir ci-bin/ && wget -O ci-bin/cr http://repo.calcit-lang.org/binaries/linux/cr
    - name: "permission"
      run: chmod +x ci-bin/cr

    - name: "prepare modules"
      run: >
        mkdir -p ~/.config/calcit/modules/ && cd ~/.config/calcit/modules/
        && git clone https://github.com/calcit-lang/lilac.git
        && git clone https://github.com/calcit-lang/memof.git
        && git clone https://github.com/calcit-lang/recollect.git
        && git clone https://github.com/Respo/respo.calcit.git
        && git clone https://github.com/Respo/respo-ui.calcit.git
        && git clone https://github.com/Respo/respo-message.calcit.git
        && git clone https://github.com/Cumulo/cumulo-util.calcit.git
        && git clone https://github.com/Cumulo/cumulo-reel.calcit.git --branch=0.0.2
        && git clone https://github.com/mvc-works/ws-edn.calcit.git

    - name: "compiles to js"
      run: >
        ./ci-bin/cr --emit-js --once --emit-path out-page/
        && ./ci-bin/cr --emit-js --once --init-fn cumulo-reel.server/main! --reload-fn cumulo-reel.server/reload!
